apiVersion: v1
kind: Service
metadata:
  name: twitter-python-service
spec:
  selector:
    app: twitter-service
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-service
spec:
  selector:
    matchLabels:
      app: twitter-service
  replicas: 1
  template:
    metadata:
      labels:
        app: twitter-service
    spec:
      containers:
      - name: twitter-service
        image: twitter-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
      